---
title: "Genre Trees - Genre Discourse Analysis"
author: "Markus Radke"
date: "`r Sys.Date()`"
format: 
    html: 
        code-fold: true
        code-summary: "Show/Hide Code"
        output-dir: reports
        toc: true
        toc-location: left
        toc-depth: 2
        number-sections: true
        theme: cosmo
        code-links:
        - text: Github Repository
          href: "https://github.com/markusradke/GenreDiscourseAnalysis"
        css: |
          .interactive-plot {
            border: 1px solid #ddd;
            border-radius: 5px;
            overflow: auto;
            max-height: 1200px;
            background-color: #fafafa;
          }
          .plot-container {
            width: 100%;
            height: 1200px;
            overflow: auto;
          }
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
devtools::load_all()
```	

# Short Explanation
include graphics from the Bayreuth Powerpoint


# Genre Tree for MusicBrainz
Only here with votes

:::{.column-screen}
```{r musicbrainz-interactive-tree, echo=FALSE}
mb_initial <- read_feather_with_lists("../models/initial_genres_mb.feather")
mb_graph <- readRDS("../models/MusicBrainz_graph.rds")

plot_network_graph(
  mb_graph,
  mb_initial,
  height = 2000,
  interactive = TRUE,
  minFontSize = 12,
  maxFontSize = 12,  # Fixed font size as requested
  sizemode = "initial_genre",
  sortmode = "size",
  fillmode = "none"
) 

```
:::

# Genre Tree for Discogs
:::{.column-screen}
```{r discogs-interactive-tree, echo=FALSE}
dc_initial <- read_feather_with_lists("../models/initial_genres_dc.feather")
dc_graph <- readRDS("../models/Discogs_graph.rds")

plot_network_graph(
  dc_graph,
  dc_initial,
  height = 2000,
  interactive = TRUE,
  minFontSize = 12,
  maxFontSize = 12,  # Fixed font size as requested
  sizemode = "initial_genre",
  sortmode = "size",
  fillmode = "none"
)
```
:::

# Genre Tree for Spotify
Please click on the nodes to explore sub-genres. The font size is fixed to ensure readability. Node size represents the number of songs in each genre.

:::{.column-screen}
```{r spotify-interactive-tree, echo=FALSE}	
s_initial <- read_feather_with_lists("../models/initial_genres_s.feather")
s_graph <- readRDS("../models/Spotify_graph.rds")

plot_network_graph(
  s_graph,
  s_initial,
  height = 1200,
  interactive = TRUE,
  minFontSize = 12,
  maxFontSize = 12,  # Fixed font size as requested
  sizemode = "initial_genre",
  sortmode = "size",
  fillmode = "none"
) 
```

:::