---
title: "Random Forest Classification - Genre Discourse Analysis"
author: "Markus Radke"
date: "`r Sys.Date()`"
format: 
    html: 
        code-fold: true
        code-summary: "Show/Hide Code"
        output-dir: reports
        toc: true
        toc-location: left
        toc-depth: 5
        toc-expand: 5
        number-sections: true
        theme: cosmo
        code-links:
        - text: Github Repository
          href: "https://github.com/markusradke/GenreDiscourseAnalysis"
        css: 
          styles.css
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
devtools::load_all()

mb_low <- readRDS("../models/classifier/rf_mb_lowres_eval.rds")
s_low <- readRDS("../models/classifier/rf_s_lowres_eval.rds")
mb_high <- readRDS("../models/classifier/rf_mb_highres_eval.rds")
s_high <- readRDS("../models/classifier/rf_s_highres_eval.rds")
```	

# Low detailed metagenres
## MusicBrainz
```{r low_results_mb}
plot_cm(mb_low$confusion, mb_low$metrics)
plot_varimp(mb_low$varimp)
```

## Spotify
```{r low_results_s}	
plot_cm(s_low$confusion, s_low$metrics)
plot_varimp(s_low$varimp)
```

# High detailed metagenre classification with Random Forest results
## MusicBrainz
```{r high_results_mb cm, fig.height=10, fig.width=12}	
plot_cm(mb_high$confusion, mb_high$metrics)
```

```{r high_results_mb varimp}	
plot_varimp(mb_high$varimp)
```

## Spotify
```{r high_results_s cm, fig.height=10, fig.width=12}
plot_cm(s_high$confusion, s_high$metrics)
```
```{r high_results_s varimp}
plot_varimp(s_high$varimp)
```
