devtools::load_all()
message("Running full replication:")
message("1. Importing and preparing data")
source("data-raw/import_and_prepare.R")
message("2. Building genre trees")
source("analysis/01_build_genre_trees.R")
message("3. Tuning tree folding")
source("analysis/02_fold_metagenres.R")
message("4. Classifying metagenres")
source("analysis/03_classify_metagenres.R")
