mb <- read_feather_with_lists('data/filtered_mb_long.feather')
dc <- read_feather_with_lists('data/filtered_dc_long.feather')
s <- read_feather_with_lists('data/filtered_s_long.feather')

message("\nBUILDING MUSICBRAINZ GENRE TREE")
build_genre_tree(mb, 'MusicBrainz', vote_weighted = TRUE)
message("\nBUILDING DISCOGS GENRE TREE")
build_genre_tree(dc, 'Discogs', vote_weighted = FALSE)
message("\nBUILDING SPOTIFY GENRE TREE")
build_genre_tree(s, 'Spotify', vote_weighted = FALSE)
